apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 4
  template:
    metadata:
      name: myapp
      labels:
         tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
