apiVersion: v1
kind: Pod
metadata:
  name: mosquito
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "app"
    operator: "equals"
    value: "app1"
    effect: "NoSchedule"
